# Generated by Django 4.0.4 on 2022-05-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('is_public', models.BooleanField(verbose_name='Is public')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Password')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
            ],
        ),
    ]
